version: 2.1

orbs:
  cypress: cypress-io/cypress@4

workflows:
  build:
    jobs:
      - cypress/run:
          # Start the app server used by E2E tests
          start-command: npm run server
          # Use project Cypress script (ensures TS config is used)
          cypress-command: npm run cypress:run
          # Optionally store Cypress artifacts
          post-steps:
            - store_artifacts:
                path: cypress/videos
            - store_artifacts:
                path: cypress/screenshots
          # If you need to pin a specific Cypress Docker image/executor, uncomment below
          # executor: cypress/default
          # tag: '18.16.0'
          # Note: Adjust executor/tag to a desired Node/Cypress image when needed
